eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/
server:
  port: 9030
spring:
  application:
    name: service-zuul
zuul:
  routes:
    api-a:
      path: /api1/**
      serviceId: consumer-ribbon
    api-b:
      path: /api2/**
      serviceId: consumer-feign